// Generated by keep_pipeline/viz/generate_viz_data.py
// DO NOT EDIT BY HAND -- regenerate from omop_graph.pkl instead.
window.graphData = {
  "stats": {
    "total_nodes": 68396,
    "total_edges": 152347,
    "leaves": 41780,
    "multi_parent": 46841,
    "root_id": 4274025,
    "root_name": "Disease",
    "max_depth": 8,
    "naive_orphans": 7,
    "naive_unreachable": 42
  },
  "depth_distribution": [
    {
      "depth": 0,
      "count": 1
    },
    {
      "depth": 1,
      "count": 169
    },
    {
      "depth": 2,
      "count": 4244
    },
    {
      "depth": 3,
      "count": 16919
    },
    {
      "depth": 4,
      "count": 24897
    },
    {
      "depth": 5,
      "count": 22137
    },
    {
      "depth": 6,
      "count": 17
    },
    {
      "depth": 7,
      "count": 10
    },
    {
      "depth": 8,
      "count": 2
    }
  ],
  "sampled_subgraph": {
    "nodes": [
      {
        "id": "4274025",
        "name": "Disease",
        "depth": 0,
        "is_root": true
      },
      {
        "id": "4143996",
        "name": "Non-allergic drug hypersensitivity disorder",
        "depth": 1,
        "is_root": false
      },
      {
        "id": "46269889",
        "name": "Complication due to Crohn's disease",
        "depth": 1,
        "is_root": false
      },
      {
        "id": "4150981",
        "name": "Drug resistance",
        "depth": 1,
        "is_root": false
      },
      {
        "id": "37167887",
        "name": "Maternal disorder during pregnancy",
        "depth": 1,
        "is_root": false
      },
      {
        "id": "37166097",
        "name": "Ataxia due to multiple system atrophy, cerebellar variant",
        "depth": 1,
        "is_root": false
      },
      {
        "id": "37311993",
        "name": "Disorder caused by stimulant",
        "depth": 1,
        "is_root": false
      },
      {
        "id": "46273477",
        "name": "Complication due to ulcerative colitis",
        "depth": 1,
        "is_root": false
      },
      {
        "id": "1245117",
        "name": "Vasopressin-related polyuria",
        "depth": 1,
        "is_root": false
      },
      {
        "id": "46269888",
        "name": "Abscess of intestine co-occurrent and due to Crohn's disease",
        "depth": 2,
        "is_root": false
      },
      {
        "id": "36686095",
        "name": "Crohn's disease of small intestine with stenosis",
        "depth": 2,
        "is_root": false
      },
      {
        "id": "4131542",
        "name": "Crohn's stricture of colon",
        "depth": 2,
        "is_root": false
      },
      {
        "id": "46269874",
        "name": "Complication due to Crohn's disease of large intestine",
        "depth": 2,
        "is_root": false
      },
      {
        "id": "46269884",
        "name": "Complication due to Crohn's disease of small intestine",
        "depth": 2,
        "is_root": false
      },
      {
        "id": "46269891",
        "name": "Rectal hemorrhage due to Crohn's disease",
        "depth": 2,
        "is_root": false
      },
      {
        "id": "37162851",
        "name": "Duodenal ulcer due to Crohn disease",
        "depth": 2,
        "is_root": false
      },
      {
        "id": "37162865",
        "name": "Gastrointestinal anastomotic ulcer due to Crohn disease",
        "depth": 2,
        "is_root": false
      },
      {
        "id": "37167166",
        "name": "Drug resistance to anti-seizure medication",
        "depth": 2,
        "is_root": false
      },
      {
        "id": "4137371",
        "name": "Drug resistance to antiretroviral therapy",
        "depth": 2,
        "is_root": false
      },
      {
        "id": "4320040",
        "name": "Increased drug resistance",
        "depth": 2,
        "is_root": false
      },
      {
        "id": "36715097",
        "name": "Resistance to antineoplastic drug",
        "depth": 2,
        "is_root": false
      },
      {
        "id": "4320041",
        "name": "Drug resistance to corticoids",
        "depth": 2,
        "is_root": false
      },
      {
        "id": "37017452",
        "name": "Drug resistance to antibacterial agent",
        "depth": 2,
        "is_root": false
      },
      {
        "id": "4318124",
        "name": "Decreased drug resistance",
        "depth": 2,
        "is_root": false
      },
      {
        "id": "40478891",
        "name": "Erythropoietin resistance in anemia of chronic kidney disease",
        "depth": 2,
        "is_root": false
      },
      {
        "id": "443404",
        "name": "Disorder of puerperium",
        "depth": 2,
        "is_root": false
      },
      {
        "id": "46269807",
        "name": "Sepsis due to ectopic pregnancy",
        "depth": 2,
        "is_root": false
      },
      {
        "id": "40539858",
        "name": "Pregnancy with abortive outcome",
        "depth": 2,
        "is_root": false
      },
      {
        "id": "443214",
        "name": "Gestational edema",
        "depth": 2,
        "is_root": false
      },
      {
        "id": "37167333",
        "name": "Disorder following ectopic pregnancy",
        "depth": 2,
        "is_root": false
      },
      {
        "id": "4029496",
        "name": "Disorder of product of conception",
        "depth": 2,
        "is_root": false
      },
      {
        "id": "4091321",
        "name": "Obstetrical tetanus",
        "depth": 2,
        "is_root": false
      },
      {
        "id": "4226262",
        "name": "Hypocalcemia of late pregnancy and/or lactation",
        "depth": 2,
        "is_root": false
      },
      {
        "id": "42539355",
        "name": "Sleep disorder caused by stimulant",
        "depth": 2,
        "is_root": false
      },
      {
        "id": "42538728",
        "name": "Disorder caused by synthetic cathinone",
        "depth": 2,
        "is_root": false
      },
      {
        "id": "42539354",
        "name": "Stimulant intoxication",
        "depth": 2,
        "is_root": false
      },
      {
        "id": "4171795",
        "name": "Psychostimulant overdose",
        "depth": 2,
        "is_root": false
      },
      {
        "id": "4203257",
        "name": "Caffeine-related disorder",
        "depth": 2,
        "is_root": false
      },
      {
        "id": "37311941",
        "name": "Impulse control disorder caused by stimulant",
        "depth": 2,
        "is_root": false
      },
      {
        "id": "42538594",
        "name": "Sexual dysfunction caused by stimulant",
        "depth": 2,
        "is_root": false
      },
      {
        "id": "606765",
        "name": "Poisoning caused by amphetamine and/or amphetamine derivative",
        "depth": 2,
        "is_root": false
      },
      {
        "id": "46269839",
        "name": "Complication due to chronic ulcerative pancolitis",
        "depth": 2,
        "is_root": false
      },
      {
        "id": "46269849",
        "name": "Complication due to chronic ulcerative rectosigmoiditis",
        "depth": 2,
        "is_root": false
      },
      {
        "id": "37162650",
        "name": "Gingival disease due to ulcerative colitis",
        "depth": 2,
        "is_root": false
      },
      {
        "id": "46269951",
        "name": "Abscess of intestine co-occurrent and due to ulcerative colitis",
        "depth": 2,
        "is_root": false
      },
      {
        "id": "37116301",
        "name": "Secondary autoimmune hemolytic anemia co-occurrent and due to ulcerative colitis",
        "depth": 2,
        "is_root": false
      },
      {
        "id": "4225691",
        "name": "Toxic megacolon due to ulcerative colitis",
        "depth": 2,
        "is_root": false
      },
      {
        "id": "46274082",
        "name": "Intestinal obstruction due to ulcerative colitis",
        "depth": 2,
        "is_root": false
      },
      {
        "id": "46273478",
        "name": "Rectal hemorrhage due to ulcerative colitis",
        "depth": 2,
        "is_root": false
      },
      {
        "id": "4297627",
        "name": "Idiopathic vasopressin-related polyuria",
        "depth": 2,
        "is_root": false
      },
      {
        "id": "438476",
        "name": "Vasopressin resistance",
        "depth": 2,
        "is_root": false
      },
      {
        "id": "1245163",
        "name": "Hereditary vasopressin-related polyuria",
        "depth": 2,
        "is_root": false
      },
      {
        "id": "1245219",
        "name": "Adipsic vasopressin-related polyuria",
        "depth": 2,
        "is_root": false
      },
      {
        "id": "4171246",
        "name": "Familial vasopressin-related polyuria",
        "depth": 2,
        "is_root": false
      },
      {
        "id": "45763617",
        "name": "Partial vasopressin-related polyuria",
        "depth": 2,
        "is_root": false
      },
      {
        "id": "4082360",
        "name": "Hypohidrosis-diabetes insipidus syndrome",
        "depth": 2,
        "is_root": false
      },
      {
        "id": "4164730",
        "name": "Vasopressin deficiency",
        "depth": 2,
        "is_root": false
      },
      {
        "id": "46274073",
        "name": "Abscess of intestine co-occurrent and due to Crohn's disease of large intestine",
        "depth": 3,
        "is_root": false
      },
      {
        "id": "46269883",
        "name": "Abscess of intestine co-occurrent and due to Crohn's disease of small intestine",
        "depth": 3,
        "is_root": false
      },
      {
        "id": "46269875",
        "name": "Fistula of large intestine due to Crohn's disease",
        "depth": 3,
        "is_root": false
      },
      {
        "id": "46269877",
        "name": "Rectal hemorrhage due to Crohn's disease of large intestine",
        "depth": 3,
        "is_root": false
      },
      {
        "id": "46269876",
        "name": "Intestinal obstruction due to Crohn's disease of large intestine",
        "depth": 3,
        "is_root": false
      },
      {
        "id": "46269879",
        "name": "Complication due to Crohn's disease of small and large intestines",
        "depth": 3,
        "is_root": false
      },
      {
        "id": "46269885",
        "name": "Fistula of small intestine due to Crohn's disease",
        "depth": 3,
        "is_root": false
      },
      {
        "id": "46269887",
        "name": "Rectal hemorrhage due to Crohn's disease of small intestine",
        "depth": 3,
        "is_root": false
      },
      {
        "id": "46269886",
        "name": "Intestinal obstruction due to Crohn's disease of small intestine",
        "depth": 3,
        "is_root": false
      },
      {
        "id": "1246786",
        "name": "Postpartum disorder of breast",
        "depth": 3,
        "is_root": false
      },
      {
        "id": "441364",
        "name": "Complication of the puerperium",
        "depth": 2,
        "is_root": false
      },
      {
        "id": "37166040",
        "name": "Postpartum substance dependence",
        "depth": 3,
        "is_root": false
      },
      {
        "id": "4100823",
        "name": "Puerperal osteomalacia",
        "depth": 3,
        "is_root": false
      },
      {
        "id": "4102318",
        "name": "Puerperal sepsis",
        "depth": 3,
        "is_root": false
      },
      {
        "id": "37167232",
        "name": "Sepsis following ectopic pregnancy",
        "depth": 3,
        "is_root": false
      },
      {
        "id": "37167975",
        "name": "Infection of pelvis due to incomplete miscarriage",
        "depth": 3,
        "is_root": false
      },
      {
        "id": "4170121",
        "name": "Retained products after miscarriage",
        "depth": 3,
        "is_root": false
      },
      {
        "id": "46269813",
        "name": "Urinary tract infection due to incomplete miscarriage",
        "depth": 3,
        "is_root": false
      },
      {
        "id": "4051244",
        "name": "Miscarriage due to Leptospira",
        "depth": 3,
        "is_root": false
      },
      {
        "id": "4323612",
        "name": "Miscarriage due to Brucella abortus",
        "depth": 3,
        "is_root": false
      },
      {
        "id": "43531709",
        "name": "Retained products of conception following induced termination of pregnancy",
        "depth": 3,
        "is_root": false
      },
      {
        "id": "37167976",
        "name": "Damage to organ of pelvis due to incomplete miscarriage",
        "depth": 3,
        "is_root": false
      },
      {
        "id": "437045",
        "name": "Embolism due to incomplete miscarriage",
        "depth": 3,
        "is_root": false
      },
      {
        "id": "1245874",
        "name": "Postpartum edema",
        "depth": 3,
        "is_root": false
      },
      {
        "id": "4058113",
        "name": "Gestational edema with proteinuria",
        "depth": 3,
        "is_root": false
      },
      {
        "id": "4208706",
        "name": "Edema of placenta",
        "depth": 3,
        "is_root": false
      },
      {
        "id": "442565",
        "name": "Gestational edema without hypertension",
        "depth": 2,
        "is_root": false
      },
      {
        "id": "42536561",
        "name": "Genital tract infection due to and following ectopic pregnancy",
        "depth": 3,
        "is_root": false
      },
      {
        "id": "45757120",
        "name": "Renal failure after ectopic pregnancy",
        "depth": 3,
        "is_root": false
      },
      {
        "id": "37167160",
        "name": "Septic shock following ectopic pregnancy",
        "depth": 3,
        "is_root": false
      },
      {
        "id": "37167309",
        "name": "Salpingitis following ectopic pregnancy",
        "depth": 3,
        "is_root": false
      },
      {
        "id": "42539701",
        "name": "Embolism due to and following ectopic pregnancy",
        "depth": 3,
        "is_root": false
      },
      {
        "id": "37167306",
        "name": "Tetanus following ectopic pregnancy",
        "depth": 3,
        "is_root": false
      },
      {
        "id": "37167174",
        "name": "Postoperative shock following ectopic pregnancy",
        "depth": 3,
        "is_root": false
      },
      {
        "id": "37167394",
        "name": "Urinary tract infection following ectopic pregnancy",
        "depth": 3,
        "is_root": false
      },
      {
        "id": "43530970",
        "name": "Gestational trophoblastic lesion",
        "depth": 2,
        "is_root": false
      },
      {
        "id": "4261479",
        "name": "Carneous mole",
        "depth": 2,
        "is_root": false
      },
      {
        "id": "4262136",
        "name": "Blighted ovum",
        "depth": 2,
        "is_root": false
      },
      {
        "id": "43530976",
        "name": "Disorder of extraembryonic membrane",
        "depth": 3,
        "is_root": false
      },
      {
        "id": "4002334",
        "name": "Detached trophoblast",
        "depth": 3,
        "is_root": false
      },
      {
        "id": "40482435",
        "name": "Residual trophoblastic disease",
        "depth": 2,
        "is_root": false
      },
      {
        "id": "4154112",
        "name": "Retained products of conception",
        "depth": 3,
        "is_root": false
      },
      {
        "id": "4053583",
        "name": "Disorder of placenta",
        "depth": 3,
        "is_root": false
      },
      {
        "id": "4267556",
        "name": "Hypocalcemia of puerperium",
        "depth": 3,
        "is_root": false
      },
      {
        "id": "4331287",
        "name": "Cocaine-induced sleep disorder",
        "depth": 3,
        "is_root": false
      },
      {
        "id": "42538741",
        "name": "Sleep disorder caused by synthetic cathinone",
        "depth": 3,
        "is_root": false
      },
      {
        "id": "4210451",
        "name": "Caffeine-induced sleep disorder",
        "depth": 3,
        "is_root": false
      },
      {
        "id": "4121694",
        "name": "Amphetamine-induced sleep disorder",
        "depth": 3,
        "is_root": false
      },
      {
        "id": "1450478",
        "name": "Sleep disorder due to stimulant dependence",
        "depth": 3,
        "is_root": false
      },
      {
        "id": "42538739",
        "name": "Obsessive compulsive disorder caused by synthetic cathinone",
        "depth": 3,
        "is_root": false
      },
      {
        "id": "42538730",
        "name": "Delirium caused by synthetic cathinone",
        "depth": 3,
        "is_root": false
      },
      {
        "id": "37311940",
        "name": "Impulse control disorder caused by synthetic cathinone",
        "depth": 3,
        "is_root": false
      },
      {
        "id": "42538731",
        "name": "Psychotic disorder caused by synthetic cathinone",
        "depth": 3,
        "is_root": false
      },
      {
        "id": "1448838",
        "name": "Synthetic cathinone use disorder",
        "depth": 3,
        "is_root": false
      },
      {
        "id": "42538738",
        "name": "Anxiety disorder caused by synthetic cathinone",
        "depth": 3,
        "is_root": false
      },
      {
        "id": "42538735",
        "name": "Mood disorder caused by synthetic cathinone",
        "depth": 3,
        "is_root": false
      },
      {
        "id": "42538841",
        "name": "Synthetic cathinone intoxication",
        "depth": 3,
        "is_root": false
      },
      {
        "id": "4101256",
        "name": "Cocaine intoxication",
        "depth": 3,
        "is_root": false
      },
      {
        "id": "607660",
        "name": "Intoxication caused by central stimulant",
        "depth": 3,
        "is_root": false
      },
      {
        "id": "1245118",
        "name": "Acute psychostimulant overdose",
        "depth": 2,
        "is_root": false
      },
      {
        "id": "4176236",
        "name": "Caffeine overdose",
        "depth": 3,
        "is_root": false
      },
      {
        "id": "4174805",
        "name": "Central nervous system stimulant overdose",
        "depth": 3,
        "is_root": false
      },
      {
        "id": "37208148",
        "name": "Intentional psychostimulant overdose",
        "depth": 3,
        "is_root": false
      },
      {
        "id": "4171797",
        "name": "Overdose of cocaine",
        "depth": 3,
        "is_root": false
      },
      {
        "id": "1448840",
        "name": "Caffeine use disorder",
        "depth": 3,
        "is_root": false
      },
      {
        "id": "4237906",
        "name": "Poisoning by caffeine",
        "depth": 3,
        "is_root": false
      },
      {
        "id": "4206433",
        "name": "Organic mental disorder caused by caffeine",
        "depth": 3,
        "is_root": false
      },
      {
        "id": "37311943",
        "name": "Impulse control disorder caused by cocaine",
        "depth": 3,
        "is_root": false
      },
      {
        "id": "42538740",
        "name": "Sexual dysfunction caused by synthetic cathinone",
        "depth": 3,
        "is_root": false
      },
      {
        "id": "600703",
        "name": "Amphetamine and/or amphetamine derivative intoxication",
        "depth": 3,
        "is_root": false
      },
      {
        "id": "37160115",
        "name": "Poisoning caused by metamfetamine",
        "depth": 3,
        "is_root": false
      },
      {
        "id": "606764",
        "name": "Accidental poisoning caused by amphetamine and/or amphetamine derivative",
        "depth": 3,
        "is_root": false
      },
      {
        "id": "3654781",
        "name": "Poisoning caused by methylenedioxymethamphetamine",
        "depth": 3,
        "is_root": false
      },
      {
        "id": "606813",
        "name": "Amphetamine and/or amphetamine derivative overdose",
        "depth": 3,
        "is_root": false
      },
      {
        "id": "606763",
        "name": "Intentional amphetamine and/or amphetamine derivative poisoning",
        "depth": 3,
        "is_root": false
      },
      {
        "id": "46269838",
        "name": "Abscess of intestine co-occurrent and due to chronic ulcerative pancolitis",
        "depth": 3,
        "is_root": false
      },
      {
        "id": "46269841",
        "name": "Rectal hemorrhage due to chronic ulcerative pancolitis",
        "depth": 3,
        "is_root": false
      },
      {
        "id": "46274069",
        "name": "Intestinal obstruction due to chronic ulcerative pancolitis",
        "depth": 3,
        "is_root": false
      },
      {
        "id": "46269840",
        "name": "Fistula of intestine due to chronic ulcerative pancolitis",
        "depth": 3,
        "is_root": false
      },
      {
        "id": "46269850",
        "name": "Fistula of large intestine due to chronic ulcerative rectosigmoiditis",
        "depth": 3,
        "is_root": false
      },
      {
        "id": "46274070",
        "name": "Intestinal obstruction due to chronic ulcerative rectosigmoiditis",
        "depth": 3,
        "is_root": false
      },
      {
        "id": "46269851",
        "name": "Rectal hemorrhage due to chronic ulcerative rectosigmoiditis",
        "depth": 3,
        "is_root": false
      },
      {
        "id": "46269848",
        "name": "Abscess of intestine co-occurrent and due to chronic ulcerative rectosigmoiditis",
        "depth": 3,
        "is_root": false
      },
      {
        "id": "1245159",
        "name": "Hereditary vasopressin resistance",
        "depth": 3,
        "is_root": false
      },
      {
        "id": "1245167",
        "name": "Secondary vasopressin resistance",
        "depth": 3,
        "is_root": false
      },
      {
        "id": "45757771",
        "name": "Partial vasopressin resistance",
        "depth": 3,
        "is_root": false
      },
      {
        "id": "37396398",
        "name": "Schofer Beetz Bohl syndrome",
        "depth": 2,
        "is_root": false
      },
      {
        "id": "4216968",
        "name": "Acquired vasopressin resistance",
        "depth": 3,
        "is_root": false
      },
      {
        "id": "37115758",
        "name": "X-linked intellectual disability, limb spasticity, retinal dystrophy, arginine vasopressin deficiency",
        "depth": 3,
        "is_root": false
      },
      {
        "id": "1245165",
        "name": "Autosomal recessive hereditary arginine vasopressin deficiency",
        "depth": 3,
        "is_root": false
      },
      {
        "id": "1245164",
        "name": "Autosomal dominant hereditary vasopressin deficiency",
        "depth": 3,
        "is_root": false
      },
      {
        "id": "4029440",
        "name": "Familial vasopressin deficiency",
        "depth": 3,
        "is_root": false
      },
      {
        "id": "1245166",
        "name": "Secondary vasopressin deficiency",
        "depth": 3,
        "is_root": false
      },
      {
        "id": "37162163",
        "name": "Vasopressin deficiency due to trauma",
        "depth": 3,
        "is_root": false
      },
      {
        "id": "46269878",
        "name": "Abscess of intestine co-occurrent and due to Crohn's disease of small and large intestine",
        "depth": 4,
        "is_root": false
      },
      {
        "id": "46269882",
        "name": "Rectal hemorrhage due to Crohn's disease of small and large intestines",
        "depth": 4,
        "is_root": false
      },
      {
        "id": "46269881",
        "name": "Intestinal obstruction due to Crohn's disease of small and large intestine",
        "depth": 4,
        "is_root": false
      },
      {
        "id": "46269880",
        "name": "Fistula of intestine due to Crohn's disease of small and large intestine",
        "depth": 4,
        "is_root": false
      },
      {
        "id": "1245853",
        "name": "Postpartum purulent mastitis",
        "depth": 3,
        "is_root": false
      },
      {
        "id": "442573",
        "name": "Nonpurulent mastitis associated with childbirth",
        "depth": 3,
        "is_root": false
      },
      {
        "id": "80796",
        "name": "Abscess of breast, associated with childbirth",
        "depth": 3,
        "is_root": false
      },
      {
        "id": "37166006",
        "name": "Postpartum cracked nipple",
        "depth": 4,
        "is_root": false
      },
      {
        "id": "4079236",
        "name": "Parenchymatous mastitis associated with childbirth",
        "depth": 3,
        "is_root": false
      },
      {
        "id": "1244146",
        "name": "Postpartum cellulitis of breast",
        "depth": 3,
        "is_root": false
      },
      {
        "id": "4232323",
        "name": "Retromammary mastitis associated with childbirth",
        "depth": 3,
        "is_root": false
      },
      {
        "id": "1245671",
        "name": "Postpartum lactation disorder",
        "depth": 4,
        "is_root": false
      },
      {
        "id": "443929",
        "name": "Postpartum hemorrhage",
        "depth": 3,
        "is_root": false
      },
      {
        "id": "74716",
        "name": "Galactorrhea associated with childbirth",
        "depth": 3,
        "is_root": false
      },
      {
        "id": "1244150",
        "name": "Postpartum cholestasis",
        "depth": 3,
        "is_root": false
      },
      {
        "id": "45757216",
        "name": "Cracked nipple associated with lactation",
        "depth": 3,
        "is_root": false
      },
      {
        "id": "4223499",
        "name": "Interstitial mastitis associated with childbirth",
        "depth": 3,
        "is_root": false
      },
      {
        "id": "1244148",
        "name": "Postpartum acute cystitis",
        "depth": 3,
        "is_root": false
      },
      {
        "id": "37116435",
        "name": "Sepsis following obstructed labor",
        "depth": 3,
        "is_root": false
      },
      {
        "id": "37167973",
        "name": "Infection of female genital tract due to incomplete miscarriage",
        "depth": 4,
        "is_root": false
      },
      {
        "id": "4062671",
        "name": "Pregnancy-induced edema and proteinuria without hypertension",
        "depth": 3,
        "is_root": false
      },
      {
        "id": "4327490",
        "name": "Hydrops of placenta",
        "depth": 4,
        "is_root": false
      },
      {
        "id": "37167336",
        "name": "Salpingo-oophoritis following ectopic pregnancy",
        "depth": 4,
        "is_root": false
      },
      {
        "id": "37167182",
        "name": "Acute renal failure following ectopic pregnancy",
        "depth": 4,
        "is_root": false
      },
      {
        "id": "37167180",
        "name": "Renal tubular necrosis following ectopic pregnancy",
        "depth": 3,
        "is_root": false
      },
      {
        "id": "3655209",
        "name": "Pulmonary embolism due to and following ectopic pregnancy",
        "depth": 4,
        "is_root": false
      },
      {
        "id": "3655206",
        "name": "Amniotic fluid embolism due to and following ectopic pregnancy",
        "depth": 4,
        "is_root": false
      },
      {
        "id": "3655212",
        "name": "Septic embolism due to and following ectopic pregnancy",
        "depth": 4,
        "is_root": false
      },
      {
        "id": "3655208",
        "name": "Blood clot embolism due to and following ectopic pregnancy",
        "depth": 4,
        "is_root": false
      },
      {
        "id": "3655216",
        "name": "Air embolism due to and following ectopic pregnancy",
        "depth": 4,
        "is_root": false
      },
      {
        "id": "3655214",
        "name": "Fat embolism due to and following ectopic pregnancy",
        "depth": 4,
        "is_root": false
      },
      {
        "id": "4216768",
        "name": "Exaggerated placental site",
        "depth": 3,
        "is_root": false
      },
      {
        "id": "4217071",
        "name": "Placental site nodule",
        "depth": 3,
        "is_root": false
      },
      {
        "id": "4214186",
        "name": "Gestational trophoblastic disease",
        "depth": 3,
        "is_root": false
      },
      {
        "id": "194702",
        "name": "Premature rupture of membranes",
        "depth": 2,
        "is_root": false
      },
      {
        "id": "619044",
        "name": "Disorder of amnion",
        "depth": 4,
        "is_root": false
      },
      {
        "id": "4304781",
        "name": "Disorder of chorion",
        "depth": 4,
        "is_root": false
      },
      {
        "id": "4069458",
        "name": "Abnormal yolk sac",
        "depth": 2,
        "is_root": false
      },
      {
        "id": "192972",
        "name": "Prolonged rupture of membranes",
        "depth": 2,
        "is_root": false
      },
      {
        "id": "606876",
        "name": "Retained products of conception with no hemorrhage",
        "depth": 4,
        "is_root": false
      },
      {
        "id": "606716",
        "name": "Retained uterine membrane",
        "depth": 4,
        "is_root": false
      },
      {
        "id": "76482",
        "name": "Missed miscarriage",
        "depth": 4,
        "is_root": false
      },
      {
        "id": "4160218",
        "name": "Retained secundines",
        "depth": 3,
        "is_root": false
      },
      {
        "id": "4069761",
        "name": "Retained fetal tissue",
        "depth": 4,
        "is_root": false
      },
      {
        "id": "4006322",
        "name": "Retained products of conception not following miscarriage or termination of pregnancy",
        "depth": 4,
        "is_root": false
      },
      {
        "id": "4036149",
        "name": "Disorder of placental circulatory function",
        "depth": 4,
        "is_root": false
      },
      {
        "id": "37162437",
        "name": "Injury of placenta",
        "depth": 2,
        "is_root": false
      },
      {
        "id": "4125613",
        "name": "Placenta fatty deposits",
        "depth": 4,
        "is_root": false
      },
      {
        "id": "4034100",
        "name": "Placental insufficiency",
        "depth": 4,
        "is_root": false
      },
      {
        "id": "200784",
        "name": "Placental condition affecting management of mother",
        "depth": 4,
        "is_root": false
      },
      {
        "id": "4009591",
        "name": "Abnormal placental secretion of chorionic gonadotropin",
        "depth": 4,
        "is_root": false
      },
      {
        "id": "4214343",
        "name": "Placentitis",
        "depth": 3,
        "is_root": false
      },
      {
        "id": "37162913",
        "name": "Placental hemorrhage",
        "depth": 4,
        "is_root": false
      },
      {
        "id": "4218738",
        "name": "Lactation tetany",
        "depth": 4,
        "is_root": false
      },
      {
        "id": "36686550",
        "name": "Sleep disorder caused by methamphetamine",
        "depth": 4,
        "is_root": false
      },
      {
        "id": "42538732",
        "name": "Psychotic disorder with hallucinations caused by synthetic cathinone",
        "depth": 4,
        "is_root": false
      },
      {
        "id": "42538734",
        "name": "Psychotic disorder with schizophreniform symptoms caused by synthetic cathinone",
        "depth": 3,
        "is_root": false
      },
      {
        "id": "42538733",
        "name": "Psychotic disorder with delusions caused by synthetic cathinone",
        "depth": 4,
        "is_root": false
      },
      {
        "id": "1448797",
        "name": "Episode of harmful use of synthetic cathinone",
        "depth": 4,
        "is_root": false
      },
      {
        "id": "42538729",
        "name": "Harmful pattern of use of synthetic cathinone",
        "depth": 4,
        "is_root": false
      },
      {
        "id": "42539370",
        "name": "Synthetic cathinone dependence",
        "depth": 4,
        "is_root": false
      },
      {
        "id": "42538737",
        "name": "Mood disorder with manic symptoms caused by synthetic cathinone",
        "depth": 4,
        "is_root": false
      },
      {
        "id": "42538736",
        "name": "Mood disorder with depressive symptoms caused by synthetic cathinone",
        "depth": 4,
        "is_root": false
      },
      {
        "id": "42539371",
        "name": "Mood disorder with mixed depressive and manic symptoms caused by synthetic cathinone",
        "depth": 4,
        "is_root": false
      },
      {
        "id": "4290062",
        "name": "Cocaine intoxication delirium",
        "depth": 4,
        "is_root": false
      },
      {
        "id": "4176237",
        "name": "Accidental caffeine overdose",
        "depth": 4,
        "is_root": false
      },
      {
        "id": "4178858",
        "name": "Intentional caffeine overdose",
        "depth": 4,
        "is_root": false
      },
      {
        "id": "36686114",
        "name": "Overdose of methylphenidate",
        "depth": 4,
        "is_root": false
      },
      {
        "id": "606815",
        "name": "Intentional amphetamine and/or amphetamine derivative overdose",
        "depth": 4,
        "is_root": false
      }
    ],
    "edges": [
      {
        "source": "4029440",
        "target": "1245165"
      },
      {
        "source": "4029440",
        "target": "1245164"
      },
      {
        "source": "4058113",
        "target": "4062671"
      },
      {
        "source": "443404",
        "target": "1246786"
      },
      {
        "source": "443404",
        "target": "441364"
      },
      {
        "source": "443404",
        "target": "37166040"
      },
      {
        "source": "443404",
        "target": "4100823"
      },
      {
        "source": "443404",
        "target": "4102318"
      },
      {
        "source": "4171795",
        "target": "1245118"
      },
      {
        "source": "4171795",
        "target": "4176236"
      },
      {
        "source": "4171795",
        "target": "4174805"
      },
      {
        "source": "4171795",
        "target": "37208148"
      },
      {
        "source": "4171795",
        "target": "4171797"
      },
      {
        "source": "441364",
        "target": "443929"
      },
      {
        "source": "441364",
        "target": "74716"
      },
      {
        "source": "441364",
        "target": "1245874"
      },
      {
        "source": "441364",
        "target": "1244150"
      },
      {
        "source": "441364",
        "target": "45757216"
      },
      {
        "source": "441364",
        "target": "4223499"
      },
      {
        "source": "441364",
        "target": "442573"
      },
      {
        "source": "441364",
        "target": "1244148"
      },
      {
        "source": "441364",
        "target": "1244146"
      },
      {
        "source": "441364",
        "target": "4079236"
      },
      {
        "source": "441364",
        "target": "4232323"
      },
      {
        "source": "441364",
        "target": "4154112"
      },
      {
        "source": "441364",
        "target": "40482435"
      },
      {
        "source": "441364",
        "target": "4267556"
      },
      {
        "source": "441364",
        "target": "37116435"
      },
      {
        "source": "46274073",
        "target": "46269878"
      },
      {
        "source": "45763617",
        "target": "45757771"
      },
      {
        "source": "46274082",
        "target": "46274069"
      },
      {
        "source": "46274082",
        "target": "46274070"
      },
      {
        "source": "4267556",
        "target": "4218738"
      },
      {
        "source": "606763",
        "target": "606815"
      },
      {
        "source": "606765",
        "target": "600703"
      },
      {
        "source": "606765",
        "target": "37160115"
      },
      {
        "source": "606765",
        "target": "606764"
      },
      {
        "source": "606765",
        "target": "3654781"
      },
      {
        "source": "606765",
        "target": "606813"
      },
      {
        "source": "606765",
        "target": "606763"
      },
      {
        "source": "4029496",
        "target": "43530970"
      },
      {
        "source": "4029496",
        "target": "4261479"
      },
      {
        "source": "4029496",
        "target": "4262136"
      },
      {
        "source": "4029496",
        "target": "43530976"
      },
      {
        "source": "4029496",
        "target": "4002334"
      },
      {
        "source": "4029496",
        "target": "40482435"
      },
      {
        "source": "4029496",
        "target": "4154112"
      },
      {
        "source": "4029496",
        "target": "4053583"
      },
      {
        "source": "1246786",
        "target": "1245853"
      },
      {
        "source": "1246786",
        "target": "442573"
      },
      {
        "source": "1246786",
        "target": "80796"
      },
      {
        "source": "1246786",
        "target": "37166006"
      },
      {
        "source": "1246786",
        "target": "4079236"
      },
      {
        "source": "1246786",
        "target": "1244146"
      },
      {
        "source": "1246786",
        "target": "4232323"
      },
      {
        "source": "1246786",
        "target": "1245671"
      },
      {
        "source": "1246786",
        "target": "74716"
      },
      {
        "source": "1246786",
        "target": "4223499"
      },
      {
        "source": "4208706",
        "target": "4327490"
      },
      {
        "source": "4053583",
        "target": "4036149"
      },
      {
        "source": "4053583",
        "target": "37162437"
      },
      {
        "source": "4053583",
        "target": "4125613"
      },
      {
        "source": "4053583",
        "target": "4034100"
      },
      {
        "source": "4053583",
        "target": "200784"
      },
      {
        "source": "4053583",
        "target": "4009591"
      },
      {
        "source": "4053583",
        "target": "4214343"
      },
      {
        "source": "4053583",
        "target": "37162913"
      },
      {
        "source": "4053583",
        "target": "4208706"
      },
      {
        "source": "4237906",
        "target": "4176236"
      },
      {
        "source": "37208148",
        "target": "606815"
      },
      {
        "source": "37208148",
        "target": "4178858"
      },
      {
        "source": "606813",
        "target": "606815"
      },
      {
        "source": "4121694",
        "target": "36686550"
      },
      {
        "source": "42538594",
        "target": "42538740"
      },
      {
        "source": "42536561",
        "target": "37167336"
      },
      {
        "source": "4164730",
        "target": "1245166"
      },
      {
        "source": "4164730",
        "target": "37115758"
      },
      {
        "source": "4164730",
        "target": "37162163"
      },
      {
        "source": "4164730",
        "target": "4029440"
      },
      {
        "source": "4101256",
        "target": "4290062"
      },
      {
        "source": "4102318",
        "target": "37116435"
      },
      {
        "source": "42539701",
        "target": "3655209"
      },
      {
        "source": "42539701",
        "target": "3655206"
      },
      {
        "source": "42539701",
        "target": "3655212"
      },
      {
        "source": "42539701",
        "target": "3655208"
      },
      {
        "source": "42539701",
        "target": "3655216"
      },
      {
        "source": "42539701",
        "target": "3655214"
      },
      {
        "source": "45757120",
        "target": "37167182"
      },
      {
        "source": "45757120",
        "target": "37167180"
      },
      {
        "source": "4150981",
        "target": "37167166"
      },
      {
        "source": "4150981",
        "target": "4137371"
      },
      {
        "source": "4150981",
        "target": "4320040"
      },
      {
        "source": "4150981",
        "target": "36715097"
      },
      {
        "source": "4150981",
        "target": "4320041"
      },
      {
        "source": "4150981",
        "target": "37017452"
      },
      {
        "source": "4150981",
        "target": "4318124"
      },
      {
        "source": "4150981",
        "target": "40478891"
      },
      {
        "source": "442565",
        "target": "4062671"
      },
      {
        "source": "438476",
        "target": "1245159"
      },
      {
        "source": "438476",
        "target": "1245167"
      },
      {
        "source": "438476",
        "target": "45757771"
      },
      {
        "source": "438476",
        "target": "37396398"
      },
      {
        "source": "438476",
        "target": "4216968"
      },
      {
        "source": "37167309",
        "target": "37167336"
      },
      {
        "source": "40539858",
        "target": "37167975"
      },
      {
        "source": "40539858",
        "target": "4170121"
      },
      {
        "source": "40539858",
        "target": "46269813"
      },
      {
        "source": "40539858",
        "target": "4051244"
      },
      {
        "source": "40539858",
        "target": "4323612"
      },
      {
        "source": "40539858",
        "target": "43531709"
      },
      {
        "source": "40539858",
        "target": "37167976"
      },
      {
        "source": "40539858",
        "target": "437045"
      },
      {
        "source": "4226262",
        "target": "4267556"
      },
      {
        "source": "43530970",
        "target": "4216768"
      },
      {
        "source": "43530970",
        "target": "4217071"
      },
      {
        "source": "43530970",
        "target": "4214186"
      },
      {
        "source": "43530976",
        "target": "194702"
      },
      {
        "source": "43530976",
        "target": "619044"
      },
      {
        "source": "43530976",
        "target": "4304781"
      },
      {
        "source": "43530976",
        "target": "4069458"
      },
      {
        "source": "43530976",
        "target": "192972"
      },
      {
        "source": "37167333",
        "target": "42536561"
      },
      {
        "source": "37167333",
        "target": "45757120"
      },
      {
        "source": "37167333",
        "target": "37167160"
      },
      {
        "source": "37167333",
        "target": "37167309"
      },
      {
        "source": "37167333",
        "target": "42539701"
      },
      {
        "source": "37167333",
        "target": "37167306"
      },
      {
        "source": "37167333",
        "target": "37167174"
      },
      {
        "source": "37167333",
        "target": "37167394"
      },
      {
        "source": "37167333",
        "target": "37167232"
      },
      {
        "source": "42538728",
        "target": "42538739"
      },
      {
        "source": "42538728",
        "target": "42538741"
      },
      {
        "source": "42538728",
        "target": "42538730"
      },
      {
        "source": "42538728",
        "target": "37311940"
      },
      {
        "source": "42538728",
        "target": "42538731"
      },
      {
        "source": "42538728",
        "target": "1448838"
      },
      {
        "source": "42538728",
        "target": "42538738"
      },
      {
        "source": "42538728",
        "target": "42538735"
      },
      {
        "source": "42538728",
        "target": "42538841"
      },
      {
        "source": "42538728",
        "target": "42538740"
      },
      {
        "source": "42538731",
        "target": "42538732"
      },
      {
        "source": "42538731",
        "target": "42538734"
      },
      {
        "source": "42538731",
        "target": "42538733"
      },
      {
        "source": "42538735",
        "target": "42538737"
      },
      {
        "source": "42538735",
        "target": "42538736"
      },
      {
        "source": "42538735",
        "target": "42539371"
      },
      {
        "source": "4203257",
        "target": "4210451"
      },
      {
        "source": "4203257",
        "target": "1448840"
      },
      {
        "source": "4203257",
        "target": "4237906"
      },
      {
        "source": "4203257",
        "target": "4206433"
      },
      {
        "source": "4154112",
        "target": "606876"
      },
      {
        "source": "4154112",
        "target": "606716"
      },
      {
        "source": "4154112",
        "target": "76482"
      },
      {
        "source": "4154112",
        "target": "43531709"
      },
      {
        "source": "4154112",
        "target": "4160218"
      },
      {
        "source": "4154112",
        "target": "4069761"
      },
      {
        "source": "4154112",
        "target": "4170121"
      },
      {
        "source": "4154112",
        "target": "4006322"
      },
      {
        "source": "37167887",
        "target": "443404"
      },
      {
        "source": "37167887",
        "target": "46269807"
      },
      {
        "source": "37167887",
        "target": "40539858"
      },
      {
        "source": "37167887",
        "target": "443214"
      },
      {
        "source": "37167887",
        "target": "37167333"
      },
      {
        "source": "37167887",
        "target": "4029496"
      },
      {
        "source": "37167887",
        "target": "4091321"
      },
      {
        "source": "37167887",
        "target": "4226262"
      },
      {
        "source": "443214",
        "target": "1245874"
      },
      {
        "source": "443214",
        "target": "4058113"
      },
      {
        "source": "443214",
        "target": "4208706"
      },
      {
        "source": "443214",
        "target": "442565"
      },
      {
        "source": "42539354",
        "target": "42538841"
      },
      {
        "source": "42539354",
        "target": "4101256"
      },
      {
        "source": "42539354",
        "target": "607660"
      },
      {
        "source": "42539355",
        "target": "4331287"
      },
      {
        "source": "42539355",
        "target": "42538741"
      },
      {
        "source": "42539355",
        "target": "4210451"
      },
      {
        "source": "42539355",
        "target": "4121694"
      },
      {
        "source": "42539355",
        "target": "1450478"
      },
      {
        "source": "37167975",
        "target": "37167973"
      },
      {
        "source": "4274025",
        "target": "4143996"
      },
      {
        "source": "4274025",
        "target": "46269889"
      },
      {
        "source": "4274025",
        "target": "4150981"
      },
      {
        "source": "4274025",
        "target": "37167887"
      },
      {
        "source": "4274025",
        "target": "37166097"
      },
      {
        "source": "4274025",
        "target": "37311993"
      },
      {
        "source": "4274025",
        "target": "46273477"
      },
      {
        "source": "4274025",
        "target": "1245117"
      },
      {
        "source": "4176236",
        "target": "4176237"
      },
      {
        "source": "4176236",
        "target": "4178858"
      },
      {
        "source": "46269807",
        "target": "37167232"
      },
      {
        "source": "37166006",
        "target": "45757216"
      },
      {
        "source": "1448838",
        "target": "1448797"
      },
      {
        "source": "1448838",
        "target": "42538729"
      },
      {
        "source": "1448838",
        "target": "42539370"
      },
      {
        "source": "46269839",
        "target": "46269838"
      },
      {
        "source": "46269839",
        "target": "46269841"
      },
      {
        "source": "46269839",
        "target": "46274069"
      },
      {
        "source": "46269839",
        "target": "46269840"
      },
      {
        "source": "46269849",
        "target": "46269850"
      },
      {
        "source": "46269849",
        "target": "46274070"
      },
      {
        "source": "46269849",
        "target": "46269851"
      },
      {
        "source": "46269849",
        "target": "46269848"
      },
      {
        "source": "607660",
        "target": "600703"
      },
      {
        "source": "46269874",
        "target": "46269875"
      },
      {
        "source": "46269874",
        "target": "46269877"
      },
      {
        "source": "46269874",
        "target": "46269876"
      },
      {
        "source": "46269874",
        "target": "46274073"
      },
      {
        "source": "46269874",
        "target": "46269879"
      },
      {
        "source": "46269876",
        "target": "46269881"
      },
      {
        "source": "46269877",
        "target": "46269882"
      },
      {
        "source": "46269879",
        "target": "46269882"
      },
      {
        "source": "46269879",
        "target": "46269878"
      },
      {
        "source": "46269879",
        "target": "46269881"
      },
      {
        "source": "46269879",
        "target": "46269880"
      },
      {
        "source": "46269883",
        "target": "46269878"
      },
      {
        "source": "46269884",
        "target": "46269883"
      },
      {
        "source": "46269884",
        "target": "46269885"
      },
      {
        "source": "46269884",
        "target": "46269887"
      },
      {
        "source": "46269884",
        "target": "46269879"
      },
      {
        "source": "46269884",
        "target": "46269886"
      },
      {
        "source": "1245117",
        "target": "4297627"
      },
      {
        "source": "1245117",
        "target": "438476"
      },
      {
        "source": "1245117",
        "target": "1245163"
      },
      {
        "source": "1245117",
        "target": "1245219"
      },
      {
        "source": "1245117",
        "target": "4171246"
      },
      {
        "source": "1245117",
        "target": "45763617"
      },
      {
        "source": "1245117",
        "target": "4082360"
      },
      {
        "source": "1245117",
        "target": "4164730"
      },
      {
        "source": "46269887",
        "target": "46269882"
      },
      {
        "source": "46269888",
        "target": "46274073"
      },
      {
        "source": "46269888",
        "target": "46269883"
      },
      {
        "source": "46269889",
        "target": "46269888"
      },
      {
        "source": "46269889",
        "target": "36686095"
      },
      {
        "source": "46269889",
        "target": "4131542"
      },
      {
        "source": "46269889",
        "target": "46269874"
      },
      {
        "source": "46269889",
        "target": "46269884"
      },
      {
        "source": "46269889",
        "target": "46269891"
      },
      {
        "source": "46269889",
        "target": "37162851"
      },
      {
        "source": "46269889",
        "target": "37162865"
      },
      {
        "source": "46269886",
        "target": "46269881"
      },
      {
        "source": "46269891",
        "target": "46269877"
      },
      {
        "source": "46269891",
        "target": "46269887"
      },
      {
        "source": "46273477",
        "target": "46269839"
      },
      {
        "source": "46273477",
        "target": "46269849"
      },
      {
        "source": "46273477",
        "target": "37162650"
      },
      {
        "source": "46273477",
        "target": "46269951"
      },
      {
        "source": "46273477",
        "target": "37116301"
      },
      {
        "source": "46273477",
        "target": "4225691"
      },
      {
        "source": "46273477",
        "target": "46274082"
      },
      {
        "source": "46273477",
        "target": "46273478"
      },
      {
        "source": "37311941",
        "target": "37311940"
      },
      {
        "source": "37311941",
        "target": "37311943"
      },
      {
        "source": "46273478",
        "target": "46269841"
      },
      {
        "source": "46273478",
        "target": "46269851"
      },
      {
        "source": "4174805",
        "target": "606813"
      },
      {
        "source": "4174805",
        "target": "36686114"
      },
      {
        "source": "1245163",
        "target": "37115758"
      },
      {
        "source": "1245163",
        "target": "1245165"
      },
      {
        "source": "1245163",
        "target": "1245164"
      },
      {
        "source": "1245163",
        "target": "1245159"
      },
      {
        "source": "4171246",
        "target": "4029440"
      },
      {
        "source": "37311993",
        "target": "42539355"
      },
      {
        "source": "37311993",
        "target": "42538728"
      },
      {
        "source": "37311993",
        "target": "42539354"
      },
      {
        "source": "37311993",
        "target": "4171795"
      },
      {
        "source": "37311993",
        "target": "4203257"
      },
      {
        "source": "37311993",
        "target": "37311941"
      },
      {
        "source": "37311993",
        "target": "42538594"
      },
      {
        "source": "37311993",
        "target": "606765"
      },
      {
        "source": "46269951",
        "target": "46269848"
      },
      {
        "source": "46269951",
        "target": "46269838"
      }
    ]
  },
  "orphan_cases": [
    {
      "orphan_id": 134736,
      "depth_from_root": 3,
      "primary_category": "outside_disease_tree",
      "filtered_parents": [
        {
          "id": 4116811,
          "name": "Pain of truncal structure",
          "domain": "Condition",
          "standard": "S",
          "vocabulary": "SNOMED",
          "class": "Clinical Finding",
          "in_node_set": false,
          "filter_reason": "outside_disease_tree"
        },
        {
          "id": 4213101,
          "name": "Finding of back",
          "domain": "Condition",
          "standard": "S",
          "vocabulary": "SNOMED",
          "class": "Clinical Finding",
          "in_node_set": false,
          "filter_reason": "outside_disease_tree"
        }
      ],
      "rescue_parents": [
        4244662
      ],
      "downstream_count": 2,
      "downstream_sample": [
        4099954,
        4133038
      ],
      "orphan_name": "Backache",
      "rescue_parent_details": [
        {
          "id": 4244662,
          "name": "Disorder of musculoskeletal system"
        }
      ],
      "downstream_sample_details": [
        {
          "id": 4099954,
          "name": "Psychogenic backache"
        },
        {
          "id": 4133038,
          "name": "Myofascial pain syndrome of lower back"
        }
      ]
    },
    {
      "orphan_id": 4090431,
      "depth_from_root": 3,
      "primary_category": "outside_disease_tree",
      "filtered_parents": [
        {
          "id": 4036154,
          "name": "Comfort alteration",
          "domain": "Condition",
          "standard": "S",
          "vocabulary": "SNOMED",
          "class": "Clinical Finding",
          "in_node_set": false,
          "filter_reason": "outside_disease_tree"
        }
      ],
      "rescue_parents": [
        4244662
      ],
      "downstream_count": 0,
      "downstream_sample": [],
      "orphan_name": "Discomfort",
      "rescue_parent_details": [
        {
          "id": 4244662,
          "name": "Disorder of musculoskeletal system"
        }
      ],
      "downstream_sample_details": []
    },
    {
      "orphan_id": 4222752,
      "depth_from_root": 1,
      "primary_category": "domain_mismatch",
      "filtered_parents": [
        {
          "id": 444194,
          "name": "Procedure related finding",
          "domain": "Observation",
          "standard": "S",
          "vocabulary": "SNOMED",
          "class": "Clinical Finding",
          "in_node_set": false,
          "filter_reason": "domain_mismatch"
        },
        {
          "id": 4105886,
          "name": "Adverse reaction",
          "domain": "Observation",
          "standard": "S",
          "vocabulary": "SNOMED",
          "class": "Disorder",
          "in_node_set": false,
          "filter_reason": "domain_mismatch"
        }
      ],
      "rescue_parents": [
        4274025
      ],
      "downstream_count": 0,
      "downstream_sample": [],
      "orphan_name": "Adverse cutaneous reaction to acupuncture",
      "rescue_parent_details": [
        {
          "id": 4274025,
          "name": "Disease"
        }
      ],
      "downstream_sample_details": []
    },
    {
      "orphan_id": 4234597,
      "depth_from_root": 2,
      "primary_category": "domain_mismatch",
      "filtered_parents": [
        {
          "id": 4042889,
          "name": "Finding relating to drug misuse behavior",
          "domain": "Observation",
          "standard": "S",
          "vocabulary": "SNOMED",
          "class": "Clinical Finding",
          "in_node_set": false,
          "filter_reason": "domain_mismatch"
        }
      ],
      "rescue_parents": [
        442019
      ],
      "downstream_count": 29,
      "downstream_sample": [
        44807040,
        45772675,
        4027653,
        4027655,
        4027657
      ],
      "orphan_name": "Misuses drugs",
      "rescue_parent_details": [
        {
          "id": 442019,
          "name": "Complication of procedure"
        }
      ],
      "downstream_sample_details": [
        {
          "id": 44807040,
          "name": "Misuses anabolic steroids"
        },
        {
          "id": 45772675,
          "name": "Misuse of analgesic"
        },
        {
          "id": 4027653,
          "name": "Long-term drug misuser"
        },
        {
          "id": 4027655,
          "name": "Misuses drugs orally"
        },
        {
          "id": 4027657,
          "name": "Misuses drugs rectally"
        }
      ]
    },
    {
      "orphan_id": 4266794,
      "depth_from_root": 6,
      "primary_category": "mixed",
      "filtered_parents": [
        {
          "id": 133280,
          "name": "Alopecia",
          "domain": "Condition",
          "standard": "S",
          "vocabulary": "SNOMED",
          "class": "Disorder",
          "in_node_set": false,
          "filter_reason": "outside_disease_tree"
        },
        {
          "id": 4323280,
          "name": "Scar of skin",
          "domain": "Observation",
          "standard": "S",
          "vocabulary": "SNOMED",
          "class": "Disorder",
          "in_node_set": false,
          "filter_reason": "domain_mismatch"
        }
      ],
      "rescue_parents": [
        133278
      ],
      "downstream_count": 13,
      "downstream_sample": [
        4033858,
        4343205,
        46273479,
        4270856,
        4301287
      ],
      "orphan_name": "Scarring alopecia",
      "rescue_parent_details": [
        {
          "id": 133278,
          "name": "Disorder of hair"
        }
      ],
      "downstream_sample_details": [
        {
          "id": 4033858,
          "name": "Acne keloidalis"
        },
        {
          "id": 4343205,
          "name": "Pseudopelade"
        },
        {
          "id": 46273479,
          "name": "Central centrifugal cicatricial alopecia"
        },
        {
          "id": 4270856,
          "name": "Cicatricial alopecia due to lichen planus"
        },
        {
          "id": 4301287,
          "name": "Cicatricial alopecia caused by ionizing radiation"
        }
      ]
    },
    {
      "orphan_id": 4276172,
      "depth_from_root": 3,
      "primary_category": "outside_disease_tree",
      "filtered_parents": [
        {
          "id": 4042142,
          "name": "Nose finding",
          "domain": "Condition",
          "standard": "S",
          "vocabulary": "SNOMED",
          "class": "Clinical Finding",
          "in_node_set": false,
          "filter_reason": "outside_disease_tree"
        }
      ],
      "rescue_parents": [
        256440
      ],
      "downstream_count": 10,
      "downstream_sample": [
        37166112,
        4218280,
        4324330,
        4167920,
        257683
      ],
      "orphan_name": "Nasal discharge",
      "rescue_parent_details": [
        {
          "id": 256440,
          "name": "Disorder of nasal sinus"
        }
      ],
      "downstream_sample_details": [
        {
          "id": 37166112,
          "name": "Cerebrospinal fluid rhinorrhea due to empty sella syndrome"
        },
        {
          "id": 4218280,
          "name": "Hemorrhagic nasal discharge"
        },
        {
          "id": 4324330,
          "name": "Cerebrospinal fluid leak from nose and mouth"
        },
        {
          "id": 4167920,
          "name": "Congenital syphilitic chronic coryza"
        },
        {
          "id": 257683,
          "name": "Posterior rhinorrhea"
        }
      ]
    },
    {
      "orphan_id": 45765791,
      "depth_from_root": 1,
      "primary_category": "domain_mismatch",
      "filtered_parents": [
        {
          "id": 441207,
          "name": "Adverse reaction to drug",
          "domain": "Observation",
          "standard": "S",
          "vocabulary": "SNOMED",
          "class": "Disorder",
          "in_node_set": false,
          "filter_reason": "domain_mismatch"
        },
        {
          "id": 4223616,
          "name": "Hypersensitivity reaction",
          "domain": "Observation",
          "standard": "S",
          "vocabulary": "SNOMED",
          "class": "Disorder",
          "in_node_set": false,
          "filter_reason": "domain_mismatch"
        }
      ],
      "rescue_parents": [
        4274025
      ],
      "downstream_count": 2,
      "downstream_sample": [
        45765792,
        45773405
      ],
      "orphan_name": "Drug reaction with eosinophilia and systemic symptoms",
      "rescue_parent_details": [
        {
          "id": 4274025,
          "name": "Disease"
        }
      ],
      "downstream_sample_details": [
        {
          "id": 45765792,
          "name": "Allopurinol hypersensitivity syndrome"
        },
        {
          "id": 45773405,
          "name": "Drug reaction with eosinophilia and systemic symptoms caused by strontium ranelate"
        }
      ]
    }
  ],
  "generated_at": "build_omop_graph 2026-04-07"
};
